### ISSUE TITLE
Who dumped the 16.00 sdk and its not "completed" 

### ISSUE THREAD

**Issue by Kian738** [Sparmage/Fortnite-SDK-Archive#3]

**Comment by gecgecgecgecgec** [comment]
What seems to be the problem with 16.00 sdk?

**Comment by Kian738** [comment]
SDK.hpp is missing and they are some files missing in the sdk like the FN_Basic

**Comment by gecgecgecgecgec** [comment]
This is for SDK.hpp https://github.com/Jacobb626/Sdk-Gen
I will look into getting the complete sdk
